version: "3.3"
services:
  authentication-service:
    container_name: authentication-service
    build: ./authentication-service
    ports:
      - "8082:8082"
    networks:
      - all-services
    depends_on:
      - mysqldb
      - gateway-authorization-service
    environment:
      eureka.client.serviceUrl.defaultZone: http://eureka-server:8761/eureka
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/mock2
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 12345
      
  checkout-service:
    container_name: checkout-service
    build: ./checkout-service
    ports:
      - "8081:8081"
    networks:
      - all-services
    depends_on:
      - mysqldb
      - eureka-server
      - gateway-authorization-service
    environment:
      eureka.client.serviceUrl.defaultZone: http://eureka-server:8761/eureka 
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/mock2
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 12345
  product-service:
    container_name: product-service
    build: ./product-service
    ports:
      - "8083:8083"
    command: chmod ugo+w /upload_mooc2/
    networks:
      - all-services
    depends_on:
      - mysqldb
      - user-service
      - eureka-server
      - gateway-authorization-service
    environment:
      eureka.client.serviceUrl.defaultZone: http://eureka-server:8761/eureka  
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/mock2
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 12345
    volumes:
      - ./upload_mooc2/:/upload_mooc2/
  eureka-server:
    container_name: eureka-server
    build: ./eureka-server
    ports:
      - "8761:8761"
    networks:
      - all-services
  gateway-authorization-service:
    container_name: gateway-authorization-service
    build: ./gateway-authorization-service
    ports:
      - "8080:8080"
    networks:
      - all-services
    depends_on:
      - eureka-server
    environment:
      eureka.client.serviceUrl.defaultZone: http://eureka-server:8761/eureka  
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/mock2
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 12345
  user-service:
    container_name: user-service
    build: ./user-service
    ports:
      - "8084:8084"
    networks:
      - all-services
    depends_on:
      - mysqldb
      - eureka-server
      - gateway-authorization-service
    environment:
      eureka.client.serviceUrl.defaultZone: http://eureka-server:8761/eureka 
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/mock2
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 12345
  mysqldb:
    container_name: mysqldb
    image: mysql:8
    ports:
      - "3307:3306"
    restart: always
    command: --init-file /docker-entrypoint-initdb.d/init.sql
    networks:
      - all-services
    volumes:
      - db:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_ROOT_PASSWORD=12345
volumes:
  db:
networks:
  all-services:
