version: "3.3"
services: 
  user-service:
    container_name: user-service
    build: ./
    ports:
      - "8080:8080"
    restart: always
    networks:
      - all-services
    depends_on:
      - mysqldb
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/mock2
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 12345
  mysqldb:
    container_name: mysqldb
    image: mysql:8
    ports:
      - "3307:3306"
    restart: always
    command: --init-file /docker-entrypoint-initdb.d/init.sql
    networks:
      - all-services
    volumes:
      - db:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_ROOT_HOST=172.18.0.3
      - MYSQL_ROOT_PASSWORD=12345
volumes:
  db:
networks:
  all-services: